module.exports = [
    {
      id: 1,
      dressname: 'Pnina Tornai',
      description: 'Only worn once. Mermaid Mikado gown with pointed deep V illusion neckline and bow detail',
      condition: 'Good',
      designer: 'Pnina Tornai',
      size: 'M',
      image: 'http://localhost:8080/images/dress1.png',
      category_id: 4,
    },
    {
      id: 2,
      dressname: 'Martina Liana',
      description: 'Only worn twice. Ballgown wedding dress with spaghetti straps',
      condition: 'Very good',
      designer: 'Martina Liana',
      size: 'S',
      image: 'http://localhost:8080/images/dress2.png',
      category_id: 2,
    },
    {
        id: 3,
        dressname: 'Love by Pnina Tornai',
        description: 'Only worn once. Simple sleeveless v-neck short wedding dress with back button detail!',
        condition: 'Good',
        designer: 'Pnina Tornai',
        size: 'S',
        image: 'http://localhost:8080/images/dress3.png',
        category_id: 3,
    },
    {
        id: 4,
        dressname: 'Martina Liana Luxe',
        description: 'Dress worn twice. A-line wedding dress with sweetheart neckline!',
        condition: 'Good',
        designer: 'Martina Liana',
        size: 'M',
        image: 'http://localhost:8080/images/dress4.png',
        category_id: 1,
    },
    {
        id: 5,
        dressname: 'All Who Wander',
        description: 'Only worn once. Floral lace A-line wedding dress with plunging v-neckline.',
        condition: 'Good',
        designer: 'All Who Wander',
        size: 'L',
        image: 'http://localhost:8080/images/dress5.png',
        category_id: 1,
    },
    {
        id: 6,
        dressname: 'Pronovias',
        description: 'Only worn twice. Long sleeve sweetheart neckline mermaid wedding dress with open back!',
        condition: 'Good',
        designer: 'Pronovias',
        size: 'S',
        image: 'http://localhost:8080/images/dress6.png',
        category_id: 4,
    },
    {
        id: 7,
        dressname: 'Pnina Tornai',
        description: 'Only worn once. Spaghetti strap short lace wedding dress with overskirt!',
        condition: 'Excellent',
        designer: 'Pnina Tornai',
        size: 'M',
        image: 'http://localhost:8080/images/dress7.png',
        category_id: 3,
    },
    {
        id: 8,
        dressname: 'Reem Acra',
        description: 'Only worn once. Jacquard off the shoulder wedding dress with ball gown skirt',
        condition: 'Good',
        designer: 'Reem Acra',
        size: 'S',
        image: 'http://localhost:8080/images/dress8.png',
        category_id: 2,
    },
  ];