module.exports = [
    {
      id: 1,
      originalprice: '800',
      buyprice: '400',
      rentprice: '100',
      user_id: 1,
      dress_id: 2,
    },
    {
        id: 2,
        originalprice: '900',
        buyprice: '450',
        rentprice: '200',
        user_id: 1,
        dress_id: 3,
    },
    {
        id: 3,
        originalprice: '700',
        buyprice: '350',
        rentprice: '80',
        user_id: 1,
        dress_id: 4,
    },
    {
        id: 4,
        originalprice: '800',
        buyprice: '400',
        rentprice: '100',
        user_id: 1,
        dress_id: 5,
      },
      {
          id: 5,
          originalprice: '900',
          buyprice: '450',
          rentprice: '200',
          user_id: 1,
          dress_id: 6,
      },
      {
          id: 6,
          originalprice: '500',
          buyprice: '250',
          rentprice: '70',
          user_id: 1,
          dress_id: 7,
      },
      {
        id: 7,
        originalprice: '950',
        buyprice: '450',
        rentprice: '150',
        user_id: 1,
        dress_id: 8,
      },
      {
          id: 8,
          originalprice: '800',
          buyprice: '400',
          rentprice: '100',
          user_id: 1,
          dress_id: 1,
      },
  ];